gui:
  showIcons: true
  theme:
    selectedLineBgColor:
      - "#4C566A"
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - "#616E88"
keybinding:
  universal:
    prevItem-alt: h
    nextItem-alt: k
    prevBlock-alt: j
    nextBlock-alt: l
    scrollUpMain-alt1: H
    scrollDownMain-alt1: K
    scrollLeft: J
    scrollRight: L
